### ISSUE TITLE
There are valid use cases for repeating a feature in a combo

### ISSUE THREAD

**Issue by thirdpolice** [SpaceCowMedia/commander-spellbook-backend#550] opened 2024-09-10 20:36 UTC
https://commanderspellbook.com/combo/2062-2584-4133/

The general implementation of this combo requires two "damage whenever a creature enters" features. At least one of them must have the "source is creature that ETBd" attribute in order to meet Soul Collector's criterion, but the second does not have this restriction.

![Screenshot 2024-09-10 at 22 33 52](https://github.com/user-attachments/assets/6ed21be1-ecc2-403f-aeb4-5a234ed77821)

**Comment by ldeluigi** [comment] 2024-09-11 00:40
Duplicate of #546

**Closed by ldeluigi** 2024-09-11 00:40 UTC
Labels: invalid
